# main.yml

name: deploy

on:
  release:
    types: [published]  # events that triggers workflows - release
  push:
    branches: [main]  # github action acts on 'main' branch.
  workflow_dispatch: # enable github action that it can be run manually.

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    environment: deploy # choosing repository's sercret environment.

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
      
    # - name: Cache JDK
      
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: ${{ secrets.JAVA_VERSION }}

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      shell: bash
      
    - name: Build with Gradle
      run: ./gradlew clean build -x test
      shell: bash

    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
    # the publishing section of your build.gradle
    - name: Publish to GitHub Packages
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
